-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 19:22:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8mb4 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`Gebruiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`Gebruiker` (
  `naam` VARCHAR(200) NULL DEFAULT NULL,
  `achternaam` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `wachtwoord` VARCHAR(200) NULL DEFAULT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`student` (
  `studentnr` VARCHAR(5) NOT NULL,
  `roepnaam` VARCHAR(10) NULL DEFAULT NULL,
  `voorletters` VARCHAR(10) NULL DEFAULT NULL,
  `tussenvoegsels` VARCHAR(8) NULL DEFAULT NULL,
  `achternaam` VARCHAR(25) NULL DEFAULT NULL,
  `adres` VARCHAR(25) NULL DEFAULT NULL,
  `postcode` VARCHAR(7) NULL DEFAULT NULL,
  `woonplaats` VARCHAR(25) NULL DEFAULT NULL,
  `geslacht` CHAR(1) NULL DEFAULT NULL,
  `telefoon` VARCHAR(11) NULL DEFAULT NULL,
  `geboortedatum` DATE NULL DEFAULT NULL,
  `uitgeschreven` DATE NULL DEFAULT NULL,
  `schoolgeld` DECIMAL(6,2) NULL DEFAULT NULL,
  `betaald` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`studentnr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
